apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-zpqz
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0003-tenant/tkrw-pr712-0075-0003-app/devfile-sample-zpqz@sha256:81e812cfe22d069f6c7e48d42efae414845fa459f1bebe08b4f5908caaa22e44
        name: my-nodejs
        resources: {}
status: {}
